### ISSUE TITLE
Restarting containers when restarting the host

### ISSUE THREAD

**Issue by javi-cs** [huntabyte/tig-stack#15]
Hi,
I have detected that when restarting the host only the Influx container starts because of the restart in the Docker Compose file, but Grafana is not activated. I have tried with the restart value but it doesn't work, is there any solution?

Thanks.

**Comment by flodek** [comment]
@javi-cs 
you mean adding `restart: unless-stopped` to telegraf and grafana sections don't work ?

**Comment by javi-cs** [comment]
@flodek I had the Compose file configured as follows and it was not working but I have solved it with what you have told me.

Thank you.

```
services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
volumes:
  grafana-storage:
  influxdb-storage:
```
